#!/bin/bash

# $1 is the path to the temporary file containing the commit message
COMMIT_MSG_FILE=$1

# Extended Regular Expression for a basic email address
EMAIL_REGEX="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"

# Use grep -v (invert match) to keep only the lines that DO NOT match the email regex.
# We save the output to a temporary file, then overwrite the original commit message.
grep -v -E "$EMAIL_REGEX" "$COMMIT_MSG_FILE" > "${COMMIT_MSG_FILE}.tmp"
mv "${COMMIT_MSG_FILE}.tmp" "$COMMIT_MSG_FILE"
